theme: jekyll-theme-slate

title: "COMP 190"
description: "Tools and Techniques for Software Development - Dickinson College"

hide_first_title: true
show_downloads: false
buttons:
  zip_hide: true
  tar_hide: true
  github_hide: true
